print("GABUNGAN")
InputData = float(input("Masukkan Data: "))
Angka1 = (InputData >= 0 and InputData <= 5)
print(Angka1)
Angka2 = (InputData >= 8 and InputData <= 11)
print(Angka2)
Hasilnya = Angka1 or Angka2 
print("Answer:", Hasilnya)
print("IRISAN") 
InputData = float(input("Masukkan Data: "))
Angka1 = (InputData <= 0 or InputData >= 5)
print(Angka1)
Angka2 = (InputData <= 8 or InputData >= 11)
print(Angka2)
Hasilnya = Angka1 and Angka2 
print("Answer:", Hasilnya)